// CED-aligned topic guide for AP Human Geography.
// Topic labels follow the public College Board Course at a Glance; explanations are original paraphrases.
(function(){
  if (window.__cedGuideInstalled) return;
  window.__cedGuideInstalled = true;

  const CED_UNITS = [
    {id:1,name:'Thinking Geographically',weight:'8–10%',topics:[
      ['1.1','Introduction to Maps','Read reference and thematic maps, recognize projection distortion, and choose a map type that matches the question.',['reference vs. thematic maps','choropleth, dot-density, isoline, cartogram','projection tradeoffs and distortion']],
      ['1.2','Geographic Data','Distinguish quantitative from qualitative evidence and understand how geographers collect, organize, and evaluate spatial data.',['census/survey and statistical data','field observations, interviews, landscapes','reliability, scale, and limitations of data']],
      ['1.3','The Power of Geographic Data','Use geospatial technologies to reveal patterns and support decisions rather than treating maps as decoration.',['GIS layers and spatial analysis','remote sensing and satellite imagery','GPS/location data and real-world applications']],
      ['1.4','Spatial Concepts','Explain location, distance, direction, distribution, and interaction using precise geographic vocabulary.',['absolute vs. relative location/distance/direction','density, concentration, pattern, clustering, dispersal','distance decay and time-space compression']],
      ['1.5','Human–Environmental Interaction','Explain how people depend on, adapt to, and modify environments without assuming the environment determines human outcomes.',['possibilism vs. environmental determinism','adaptation and modification','sustainability and environmental consequences']],
      ['1.6','Scales of Analysis','Explain why the same pattern can look different at local, regional, national, and global scales.',['levels of analysis','aggregation can hide local variation','avoid making claims at a scale the evidence does not support']],
      ['1.7','Regional Analysis','Use regions as analytical tools and distinguish how regions are created and perceived.',['formal regions','functional regions and nodes','perceptual/vernacular regions and changing boundaries']]
    ]},
    {id:2,name:'Population and Migration Patterns and Processes',weight:'12–17%',topics:[
      ['2.1','Population Distribution','Explain where people live and why population is unevenly distributed.',['ecumene and physical constraints','arithmetic, physiological, and agricultural density','clustering near resources, coasts, rivers, and economic opportunity']],
      ['2.2','Consequences of Population Distribution','Connect density and distribution to economic, political, social, and environmental outcomes.',['pressure on land, water, housing, and infrastructure','access to markets, services, and jobs','carrying capacity and uneven impacts']],
      ['2.3','Population Composition','Interpret the age and sex structure of a population and infer likely needs or future change.',['population pyramids','sex ratio and age cohorts','dependency ratio, youth bulges, and aging']],
      ['2.4','Population Dynamics','Calculate or interpret the measures that explain population growth and decline.',['CBR, CDR, TFR, NIR, IMR, life expectancy','doubling time and replacement fertility','natural increase vs. migration']],
      ['2.5','The Demographic Transition Model','Use the DTM to connect development with changing birth and death rates, while recognizing that the model is a generalization.',['stages and rate patterns','why death rates usually fall before birth rates','limitations and possible Stage 5 patterns']],
      ['2.6','Malthusian Theory','Compare population-resource arguments and evaluate how technology, consumption, and distribution affect carrying capacity.',['Malthus: population can outpace food supply','neo-Malthusian resource concerns','technology/innovation can raise productivity but not erase distribution problems']],
      ['2.7','Population Policies','Explain why governments use population policies and evaluate intended and unintended effects.',['pronatalist and antinatalist policies','immigration restrictions or incentives','economic, gender, and age-structure consequences']],
      ['2.8','Women and Demographic Change','Explain how women’s access to education, employment, health care, and political power changes demographic patterns.',['female education and later family formation','employment/opportunity and lower fertility','maternal health, child survival, and development']],
      ['2.9','Aging Populations','Explain the causes and consequences of population aging and compare possible policy responses.',['low fertility plus longer life expectancy','pensions, health care, dependency, labor shortages','immigration, retirement-age, family-support, and automation policies']],
      ['2.10','Causes of Migration','Explain migration decisions using economic, political, cultural, demographic, and environmental factors.',['push and pull factors','intervening obstacles and opportunities','chain, step, and rural-to-urban migration']],
      ['2.11','Forced and Voluntary Migration','Distinguish migration by degree of choice and legal/geographic status.',['refugees, asylum seekers, and internally displaced people','forced migration from conflict, persecution, or disasters','voluntary migration for work, school, family, or amenities']],
      ['2.12','Effects of Migration','Explain migration impacts on both origins and destinations at multiple scales.',['remittances and household/local development','brain drain, brain gain, and labor-market change','cultural diffusion, demographic change, and political response']]
    ]},
    {id:3,name:'Cultural Patterns and Processes',weight:'12–17%',topics:[
      ['3.1','Introduction to Culture','Explain culture as a system of learned traits expressed differently across space.',['cultural traits and complexes','folk/local vs. popular/global culture','ethnicity, identity, and cultural practice']],
      ['3.2','Cultural Landscapes','Read the built environment as evidence of culture, history, identity, and power.',['architecture, land use, language, religion, and toponyms','sequent occupance and layered landscapes','gendered and ethnic landscapes']],
      ['3.3','Cultural Patterns','Describe and explain spatial patterns of language, religion, ethnicity, and other cultural traits.',['language families/branches and dialects','universalizing vs. ethnic religions','distribution reflects migration, history, and interaction']],
      ['3.4','Types of Diffusion','Choose the correct diffusion process and explain how it changes spatial patterns.',['relocation diffusion','contagious and hierarchical expansion diffusion','stimulus diffusion and adaptation']],
      ['3.5','Historical Causes of Diffusion','Explain how past migration, conquest, colonialism, trade, and state power spread cultural traits.',['imperialism/colonialism','migration and diaspora','trade routes, conquest, and missionary activity']],
      ['3.6','Contemporary Causes of Diffusion','Explain how technology and globalization accelerate, redirect, or resist cultural diffusion.',['social media and communication networks','travel, trade, multinational firms, and cities','time-space compression and unequal access']],
      ['3.7','Diffusion of Religion and Language','Apply diffusion concepts specifically to language and religion.',['hearths and migration routes','lingua franca, pidgin/creole, and official language','universalizing religions spread differently from ethnic religions']],
      ['3.8','Effects of Diffusion','Evaluate how diffusion can produce both cultural mixing and cultural tension.',['acculturation, assimilation, syncretism','cultural convergence and divergence','placelessness, revival, resistance, and identity change']]
    ]},
    {id:4,name:'Political Patterns and Processes',weight:'12–17%',topics:[
      ['4.1','Introduction to Political Geography','Use political-geography vocabulary precisely before explaining more complex political patterns.',['state, nation, nation-state','stateless nation, multinational state, multistate nation','sovereignty and self-determination']],
      ['4.2','Political Processes','Explain how nationalism, colonialism, decolonization, and supranational cooperation reshape political space.',['colonialism/imperialism and decolonization','nationalism and self-determination','supranationalism and democratization']],
      ['4.3','Political Power and Territoriality','Explain how states and groups control territory, resources, access, and strategic locations.',['territoriality','choke points and strategic resources','maritime claims, territorial seas, and EEZs']],
      ['4.4','Defining Political Boundaries','Classify boundaries by how and when they were created and recognize that boundary origins can shape later conflict.',['antecedent, subsequent/consequent, superimposed, relic','geometric vs. cultural boundaries','demarcation and boundary landscapes']],
      ['4.5','The Function of Political Boundaries','Explain how boundaries regulate movement, trade, security, identity, and resources.',['open vs. restricted movement','boundary disputes over location, operation, and resources','borders can both connect and divide regions']],
      ['4.6','Internal Boundaries','Explain how internal political lines distribute representation and governmental power.',['federal vs. unitary organization','reapportionment and redistricting','gerrymandering: packing and cracking']],
      ['4.7','Forms of Governance','Compare how political authority is organized and why different systems fit different states.',['federal and unitary systems','local autonomy and scale of government','governance can strengthen or weaken cohesion']],
      ['4.8','Defining Devolutionary Factors','Explain why power moves away from a central state or why states fragment.',['physical separation and distance','ethnic separatism, irredentism, and ethnonationalism','economic/social problems, conflict, terrorism, and ethnic cleansing']],
      ['4.9','Challenges to Sovereignty','Explain how devolution, technology, globalization, and supranational organizations constrain state action.',['autonomous/semi-autonomous regions','communication technology and democratization','UN, NATO, EU, ASEAN, African Union and other supranational groups']],
      ['4.10','Consequences of Centrifugal and Centripetal Forces','Apply unifying and dividing forces to outcomes at the state scale.',['centrifugal forces: fragmentation, stateless nations, uneven development','centripetal forces: cohesion, shared institutions, infrastructure','the same factor can unify one group while dividing another']]
    ]},
    {id:5,name:'Agriculture and Rural Land-Use Patterns and Processes',weight:'12–17%',topics:[
      ['5.1','Introduction to Agriculture','Distinguish major agricultural systems and connect them to land, labor, capital, market orientation, and culture.',['subsistence vs. commercial','intensive vs. extensive','crop, livestock, and mixed systems']],
      ['5.2','Settlement Patterns and Survey Methods','Recognize rural settlement patterns and how land-survey systems shape landscapes.',['clustered, dispersed, and linear settlement','metes-and-bounds','township-and-range and long-lot patterns']],
      ['5.3','Agricultural Origins and Diffusions','Explain the shift to agriculture and how domesticated plants and animals spread.',['domestication and agricultural hearths','First Agricultural/Neolithic Revolution','diffusion and the Columbian Exchange']],
      ['5.4','The Second Agricultural Revolution','Connect agricultural innovation to industrialization, urban growth, and rising food supply.',['crop rotation and selective breeding','enclosure, mechanization, and improved tools','transportation improvements and growing urban markets']],
      ['5.5','The Green Revolution','Evaluate both the gains and costs of high-input agricultural technology.',['high-yield varieties, irrigation, fertilizer, pesticides','higher yields and expanded carrying capacity','cost, inequality, water use, soil damage, and chemical pollution']],
      ['5.6','Agricultural Production Regions','Match production systems to climate, culture, labor, market, and level of development.',['pastoral nomadism, shifting cultivation, intensive subsistence','plantations, mixed crop/livestock, grain, dairy, ranching','Mediterranean agriculture, market gardening, aquaculture']],
      ['5.7','Spatial Organization of Agriculture','Explain why agricultural activities locate where they do and how producers connect to markets.',['climate, land value, labor, capital, and transport','commodity chains and agribusiness','distance, perishability, and market access']],
      ['5.8','Von Thünen Model','Use the model to explain agricultural land use, then state when real-world conditions break its assumptions.',['market at the center and land-rent gradient','transport cost and perishability shape rings','roads, refrigeration, terrain, multiple markets, and globalization modify the pattern']],
      ['5.9','The Global System of Agriculture','Explain how global trade links food-producing and food-consuming regions.',['agribusiness and vertically connected supply chains','specialization, comparative advantage, and trade','corporate power, food miles, and interdependence']],
      ['5.10','Consequences of Agricultural Practices','Trace agricultural practices to environmental and social outcomes.',['deforestation, erosion, desertification, and biodiversity loss','irrigation, salinization, water depletion, fertilizer/pesticide runoff','monoculture, GMOs, and changing rural livelihoods']],
      ['5.11','Challenges of Contemporary Agriculture','Evaluate food-access and sustainability challenges rather than assuming greater production automatically solves hunger.',['food insecurity and unequal access/distribution','climate change, soil/water stress, and disease risk','local/organic farming, conservation, sustainable agriculture, and technology']],
      ['5.12','Women in Agriculture','Explain how gender roles and access to land/resources affect agricultural productivity and development.',['women’s labor in subsistence and commercial systems','land ownership, credit, technology, and education gaps','greater access can raise food security and household development']]
    ]},
    {id:6,name:'Cities and Urban Land-Use Patterns and Processes',weight:'12–17%',topics:[
      ['6.1','The Origin and Influences of Urbanization','Explain why cities emerged and why urbanization accelerated with economic change.',['agricultural surplus and early urban hearths','industrialization and rural-to-urban migration','site, situation, transportation, and economic functions']],
      ['6.2','Cities Across the World','Compare urbanization patterns at different levels of development.',['percent urban vs. rate of urban growth','megacities/metacities and rapid growth','informal settlements and infrastructure gaps']],
      ['6.3','Cities and Globalization','Explain how world cities organize global flows of capital, information, people, and services.',['world/global cities and urban hierarchy','networks and linkages among cities','finance, culture, transport, and corporate command functions']],
      ['6.4','The Size and Distribution of Cities','Use urban-size theories to explain city spacing, hierarchy, and interaction.',['rank-size rule and primate city','gravity model','Christaller central place theory, threshold, and range']],
      ['6.5','The Internal Structure of Cities','Use urban models as simplified explanations, compare their assumptions, and identify where they fit poorly.',['Burgess concentric-zone, Hoyt sector, Harris-Ullman multiple-nuclei','galactic city and bid-rent theory','Latin American, Southeast Asian, and African urban models']],
      ['6.6','Density and Land Use','Explain how residential density and building form reflect culture, technology, development cycles, and land value.',['low-, medium-, and high-density housing','infilling and redevelopment','land-use intensity changes with accessibility and value']],
      ['6.7','Infrastructure','Connect the location and quality of infrastructure to economic opportunity, social equity, politics, and the environment.',['transportation, water, sewer, power, communication','unequal access can reproduce spatial inequality','infrastructure investments reshape growth patterns']],
      ['6.8','Urban Sustainability','Evaluate urban-design strategies using both benefits and tradeoffs.',['mixed use, walkability, transit-oriented development','New Urbanism, greenbelts, smart/slow growth','benefits can include less sprawl; costs can include higher housing prices or displacement']],
      ['6.9','Urban Data','Use both quantitative and qualitative evidence to explain urban change.',['census and survey data show population size/composition','field studies and narratives reveal attitudes and lived experience','compare multiple sources and note scale/limitations']],
      ['6.10','Challenges of Urban Changes','Explain causes and consequences of social and economic change within cities and evaluate responses.',['redlining, blockbusting, affordability, service access, environmental injustice','squatter settlements, land tenure, disamenity zones','urban renewal/gentrification, inclusionary zoning, local food movements, fragmented governance']],
      ['6.11','Challenges of Urban Sustainability','Evaluate attempts to address environmental pressures created by urban growth.',['sprawl, sanitation, climate change, air/water quality, energy/ecological footprint','brownfield remediation and redevelopment','urban growth boundaries, regional planning, and farmland protection']]
    ]},
    {id:7,name:'Industrial and Economic Development Patterns and Processes',weight:'12–17%',topics:[
      ['7.1','The Industrial Revolution','Explain why industrialization began in particular places and how it diffused and transformed landscapes.',['coal, iron, capital, labor, transportation, and markets','diffusion of manufacturing and new industrial regions','urbanization, labor change, and environmental impacts']],
      ['7.2','Economic Sectors and Patterns','Classify economic activity and explain how sectoral structure changes with development.',['primary, secondary, tertiary, quaternary, quinary','formal vs. informal economic activity','industrial location factors, agglomeration, and changing labor geography']],
      ['7.3','Measures of Development','Compare multiple measures and explain why no single statistic captures development.',['GDP/GNI per capita and sector structure','HDI: income, education, life expectancy','GII and other social measures; averages can hide regional and gender inequality']],
      ['7.4','Women and Economic Development','Explain how gender equity both reflects and influences development.',['education, labor-force participation, political representation','fertility and health outcomes','access to credit/property and the Gender Inequality Index']],
      ['7.5','Theories of Development','Apply development theories and critique their assumptions.',['Rostow stages of economic growth','dependency/world-systems: core, semi-periphery, periphery','models simplify reality; compare strengths, weaknesses, and scale']],
      ['7.6','Trade and the World Economy','Explain how trade and the international division of labor connect places while creating winners and losers.',['comparative advantage, specialization, tariffs, and trade agreements','multinational corporations, FDI, outsourcing, and global supply chains','new international division of labor and uneven bargaining power']],
      ['7.7','Changes as a Result of the World Economy','Explain how globalization changes industrial location, work, and regional economies.',['deindustrialization and restructuring','Fordist to post-Fordist/flexible production and just-in-time systems','EPZs/SEZs, maquiladoras, multiplier effects, and environmental/social consequences']],
      ['7.8','Sustainable Development','Evaluate development strategies across economic, social, and environmental goals and across scales.',['renewable energy, conservation, and lower-impact production','education, health, microfinance, fair trade, and human capital','development choices involve tradeoffs among growth, equity, and environmental protection']]
    ]}
  ];

  const CED_SKILLS = [
    ['1','Concepts and Processes','Analyze geographic concepts, processes, models, and theories in both abstract and real situations.','Do not stop at a definition: apply the idea, explain cause/effect, and identify a model’s limitation.'],
    ['2','Spatial Relationships','Explain patterns, relationships, and likely outcomes in a specific geographic context.','Use WHERE + PATTERN + WHY. Tie your explanation to the place or scenario given.'],
    ['3','Data Analysis','Read quantitative and geospatial data in maps, tables, charts, graphs, and infographics.','State the pattern with evidence first, then explain what could cause it; note data limitations.'],
    ['4','Source Analysis','Interpret qualitative information in maps, images, landscapes, cartoons, and other visual sources.','Point to a visible feature, connect it to a geographic concept, and explain what the source cannot prove.'],
    ['5','Scale Analysis','Explain how a pattern or process changes across local, regional, national, and global scales.','Name the scale, compare it with another scale, and explain why aggregation or context changes the conclusion.']
  ];

  const STORE_KEY='aphgCedConfidenceV1';
  let cedUnit='all';
  let cedQuery='';
  let cedNeedsWork=false;
  let cedMode='topics';

  function cedState(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||'{}')}catch(e){return {}}}
  function saveCedState(s){localStorage.setItem(STORE_KEY,JSON.stringify(s));}
  function toggleCed(id){const s=cedState();s[id]=!s[id];saveCedState(s);render();}
  function resetCed(){if(confirm('Clear your CED confidence checkmarks?')){localStorage.removeItem(STORE_KEY);render();}}
  function setCedUnit(v){cedUnit=v;render();}
  function setCedQuery(v){cedQuery=v;render();}
  function setCedNeeds(v){cedNeedsWork=v;render();}
  function setCedMode(v){cedMode=v;render();}

  window.toggleCed=toggleCed; window.resetCed=resetCed; window.setCedUnit=setCedUnit; window.setCedQuery=setCedQuery; window.setCedNeeds=setCedNeeds; window.setCedMode=setCedMode;
  window.APHGCEDGuide={allTopics:allCedTopics,openTopic(id){const t=allCedTopics().find(x=>x.id===id);if(!t)return;cedMode='topics';cedUnit=String(t.unit);cedQuery=t.id;cedNeedsWork=false;active='ced';render();}};

  function allCedTopics(){return CED_UNITS.flatMap(u=>u.topics.map(t=>({unit:u.id,unitName:u.name,weight:u.weight,id:t[0],title:t[1],summary:t[2],must:t[3]})));}
  function cedPercent(){const s=cedState(),all=allCedTopics();const done=all.filter(t=>s[t.id]).length;return {done,total:all.length,pct:Math.round(done/all.length*100)};}
  function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

  function examReadinessCard(){const p=cedPercent();return `<section class="card ced-hero"><div><div class="ced-kicker">CED-aligned coverage tracker</div><h2>🎯 Know the whole course — then practice using it</h2><p>This guide maps the Study Buddy to all ${p.total} public CED topics. A checkmark means <b>you can explain and apply the topic without notes</b>, not merely recognize the vocabulary.</p></div><div class="ced-score"><b>${p.pct}%</b><span>${p.done}/${p.total} topics confident</span></div></section>`;}

  function cedTabs(){return `<div class="ced-subnav"><button class="${cedMode==='topics'?'active':''}" onclick="setCedMode('topics')">68 CED Topics</button><button class="${cedMode==='skills'?'active':''}" onclick="setCedMode('skills')">5 AP Skills</button><button class="${cedMode==='exam'?'active':''}" onclick="setCedMode('exam')">Exam Game Plan</button></div>`;}

  function topicsView(){
    const s=cedState(); const q=cedQuery.trim().toLowerCase();
    const rows=allCedTopics().filter(t=>(cedUnit==='all'||String(t.unit)===String(cedUnit)) && (!q||(`${t.id} ${t.title} ${t.summary} ${t.must.join(' ')}`).toLowerCase().includes(q)) && (!cedNeedsWork||!s[t.id]));
    const unitButtons=['<button class="'+(cedUnit==='all'?'active':'')+'" onclick="setCedUnit(\'all\')">All units</button>'].concat(CED_UNITS.map(u=>`<button class="${String(cedUnit)===String(u.id)?'active':''}" onclick="setCedUnit('${u.id}')">U${u.id}</button>`)).join('');
    return `<section class="card"><div class="ced-controls"><div class="ced-unit-filter">${unitButtons}</div><input class="ced-search" aria-label="Search CED topics" placeholder="Search topic or concept..." value="${esc(cedQuery)}" oninput="setCedQuery(this.value)"><label class="ced-check"><input type="checkbox" ${cedNeedsWork?'checked':''} onchange="setCedNeeds(this.checked)"> Show only needs work</label></div><p class="ced-small">Tip: mark a topic only when you can <b>define it, recognize it in a stimulus, and explain a geographic cause or effect</b>.</p></section>
    <div class="ced-topic-grid">${rows.map(t=>`<article class="card ced-topic ${s[t.id]?'done':''}"><div class="ced-topic-head"><div><span class="pill">Unit ${t.unit} · ${t.weight}</span><h3>${t.id} ${t.title}</h3></div><button class="ced-confidence" onclick="toggleCed('${t.id}')" aria-label="Toggle confidence for ${esc(t.id)}">${s[t.id]?'✅ Confident':'⬜ Mark confident'}</button></div><p>${t.summary}</p><div class="ced-must"><b>Be able to use:</b><ul>${t.must.map(x=>`<li>${x}</li>`).join('')}</ul></div></article>`).join('')||'<section class="card"><p>No topics match those filters.</p></section>'}</div><section class="card"><button class="btn-secondary" onclick="resetCed()">Reset CED checkmarks</button></section>`;
  }

  function skillsView(){return `<section class="card"><h2>The test is not a vocabulary test</h2><p>College Board assesses five skill categories across the year. If you know every term but cannot read a stimulus, explain a spatial relationship, or switch scales, you are not exam-ready.</p></section><div class="ced-topic-grid">${CED_SKILLS.map(s=>`<article class="card ced-skill"><span class="pill">Skill ${s[0]}</span><h3>${s[1]}</h3><p>${s[2]}</p><div class="box-good"><b>How to practice:</b> ${s[3]}</div></article>`).join('')}</div><section class="card"><h3>Command words that matter</h3><div class="ced-command-grid"><div><b>Identify</b><span>Name it directly. No extra explanation required unless asked.</span></div><div><b>Describe</b><span>Give relevant characteristics or a spatial pattern with specific evidence.</span></div><div><b>Explain</b><span>Show how or why. Use a clear cause → mechanism → result chain.</span></div><div><b>Compare</b><span>State a meaningful similarity and/or difference using the same criterion.</span></div></div></section>`;}

  function examView(){return `<section class="card"><h2>AP Human Geography exam game plan</h2><p>The current College Board format is fully digital and keeps a stable structure: <b>60 multiple-choice questions in 60 minutes (50%)</b> and <b>3 FRQs in 75 minutes (50%)</b>. Roughly 30–40% of MCQs use stimulus material.</p><div class="ced-exam-grid"><div class="box-info"><h3>MCQ</h3><p><b>Average pace:</b> about 1 minute per question.</p><p>Expect maps, charts, tables, graphs, images, infographics, and landscapes. Read the question first, then interrogate the stimulus.</p></div><div class="box-info"><h3>FRQ</h3><p><b>Q1:</b> no stimulus<br><b>Q2:</b> 1 stimulus<br><b>Q3:</b> 2 stimuli</p><p>At least one FRQ requires analysis across geographic scales.</p></div></div></section><section class="card"><h3>A pass-focused routine</h3><ol class="ced-plan"><li><b>Content:</b> work through all 68 CED topics. Do not skip a unit because its weight is smaller.</li><li><b>Retrieval:</b> use Key Terms until you can define concepts without choices in front of you.</li><li><b>Application:</b> use Practice Quiz and AP Mastery to answer stimulus-based questions, not just definition questions.</li><li><b>FRQ:</b> practice all three FRQ types. For every “explain,” write a cause/effect connection, not a list.</li><li><b>Error log:</b> after every miss, decide whether the problem was content, stimulus reading, scale, or command-word execution.</li><li><b>Full practice:</b> use the simulator under time pressure only after you have built broad topic coverage.</li></ol><div class="box-warn"><b>Important:</b> No study site can guarantee a passing score. The best predictor we can build here is broad CED coverage plus repeated AP-style application and correction of mistakes.</div></section>`;}

  function cedPage(){return `<main>${examReadinessCard()}${cedTabs()}${cedMode==='topics'?topicsView():cedMode==='skills'?skillsView():examView()}<section class="card ced-source"><b>Alignment note:</b> Topic names are aligned to the public College Board AP Human Geography Course and Exam Description / Course at a Glance. Explanations on this page are original paraphrases for studying. Study Buddy is not affiliated with College Board.</section></main>`;}
  window.cedPage=cedPage;

  const style=document.createElement('style');
  style.textContent=`
    .ced-hero{display:flex;gap:24px;align-items:center;justify-content:space-between;background:linear-gradient(135deg,#ecfeff,#eff6ff)}
    .ced-kicker{text-transform:uppercase;letter-spacing:.08em;font-size:12px;font-weight:800;color:#0f766e}.ced-score{min-width:150px;text-align:center;background:white;border:1px solid #cbd5e1;border-radius:16px;padding:16px}.ced-score b{display:block;font-size:34px;color:#0f766e}.ced-score span{font-size:12px;color:#475569}.ced-subnav{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.ced-subnav button,.ced-unit-filter button{border:1px solid #cbd5e1;background:white;border-radius:999px;padding:8px 12px;font-weight:700;cursor:pointer}.ced-subnav button.active,.ced-unit-filter button.active{background:#0f766e;color:white;border-color:#0f766e}.ced-controls{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.ced-unit-filter{display:flex;gap:6px;flex-wrap:wrap}.ced-search{flex:1;min-width:220px;border:1px solid #cbd5e1;border-radius:10px;padding:10px 12px}.ced-check{font-size:14px}.ced-small{font-size:13px;color:#475569;margin-bottom:0}.ced-topic-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:12px}.ced-topic{margin:0}.ced-topic.done{outline:2px solid #86efac;background:#f0fdf4}.ced-topic-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.ced-topic-head h3{margin:8px 0}.ced-confidence{border:1px solid #cbd5e1;background:white;border-radius:10px;padding:8px 10px;font-weight:700;white-space:nowrap;cursor:pointer}.ced-must{background:#f8fafc;border-radius:10px;padding:10px 12px}.ced-must ul{margin:6px 0 0;padding-left:20px}.ced-must li{margin:4px 0}.ced-command-grid,.ced-exam-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.ced-command-grid>div{border:1px solid #e2e8f0;border-radius:10px;padding:12px}.ced-command-grid b,.ced-command-grid span{display:block}.ced-command-grid span{font-size:13px;color:#475569;margin-top:4px}.ced-plan li{margin:8px 0}.ced-source{font-size:12px;color:#64748b}.ced-skill{margin:0}@media(max-width:650px){.ced-hero{align-items:flex-start;flex-direction:column}.ced-score{width:100%}.ced-topic-head{flex-direction:column}.ced-confidence{width:100%}}
  `;
  document.head.appendChild(style);

  if (typeof tabs!=='undefined' && !tabs.some(t=>t[0]==='ced')) tabs.splice(4,0,['ced','🎯 CED Guide']);
  const baseRender=render;
  render=function(){
    if(active==='ced'){
      renderNav();
      document.getElementById('app').innerHTML=cedPage();
      return;
    }
    return baseRender();
  };
  renderNav();
})();
