// AP-style stimulus practice lab. All stimuli and questions are original.
(function(){
  if(window.__examLabInstalled || typeof tabs==='undefined' || typeof render==='undefined') return;
  window.__examLabInstalled=true;
  tabs.splice(Math.max(1,tabs.length-1),0,['examLab','🧪 Exam Lab']);

  const sets=[
    {unit:1,title:'Scale and Spatial Data',stimulus:`<table class="simple-table"><tr><th>Area</th><th>Median commute</th><th>Transit share</th></tr><tr><td>Metro region</td><td>31 min</td><td>14%</td></tr><tr><td>Central city</td><td>24 min</td><td>32%</td></tr><tr><td>Outer suburb</td><td>39 min</td><td>4%</td></tr></table>`,qs:[
      ['Which conclusion is best supported by the table?',['Travel behavior varies by scale and subregion','The entire metro has identical transit access','Transit use causes all commute differences','Outer suburbs are formal regions'],'Travel behavior varies by scale and subregion','The regional average hides important local differences.'],
      ['Which additional GIS layer would best help explain the suburban pattern?',['Transit routes and job locations','Religious affiliation','Birth rates by country','State boundaries only'],'Transit routes and job locations','Transit and employment access directly relate to commute patterns.'],
      ['A claim based only on the metro-wide average would risk which error?',['Ignoring scale of analysis','Confusing nation and state','Using relocation diffusion','Applying the DTM'],'Ignoring scale of analysis','Aggregated data can hide neighborhood or subregional variation.']]},
    {unit:2,title:'Population Structure',stimulus:`<table class="simple-table"><tr><th>Year</th><th>TFR</th><th>Age 65+</th><th>Net migration/1,000</th></tr><tr><td>2000</td><td>2.1</td><td>11%</td><td>1</td></tr><tr><td>2025</td><td>1.4</td><td>22%</td><td>2</td></tr></table>`,qs:[
      ['Which trend is most evident?',['Population aging','A growing youth bulge','Stage 2 growth','Rapidly rising fertility'],'Population aging','Low fertility and a larger elderly share indicate aging.'],
      ['Which policy would most directly address a shrinking workforce?',['Encourage working-age immigration','Reduce female education','Restrict all labor-force participation','Increase infant mortality'],'Encourage working-age immigration','Working-age migrants can reduce labor shortages.'],
      ['Which measure would best show pressure created by dependents?',['Dependency ratio','Arithmetic density','Sex ratio only','Doubling time only'],'Dependency ratio','Dependency ratio compares dependent ages with the working-age population.']]},
    {unit:3,title:'Cultural Diffusion Network',stimulus:`<div class="box-info"><b>Observed pattern:</b> A music style begins in City A, becomes popular among national celebrities, spreads to major cities, and is later adapted into local-language versions in smaller markets.</div>`,qs:[
      ['The first spread from celebrities to major cities is best described as...',['Hierarchical diffusion','Relocation diffusion','Contagious diffusion only','Environmental determinism'],'Hierarchical diffusion','The trait spreads through influential people and high-order places.'],
      ['Local-language adaptations are best explained by...',['Stimulus diffusion','Assimilation only','Distance decay','Devolution'],'Stimulus diffusion','The core idea spreads but changes to fit local culture.'],
      ['Which process could make the pattern spread faster across long distances?',['Time-space compression','Physiological density','Reapportionment','Bid-rent'],'Time-space compression','Media and communication reduce the friction of distance.']]},
    {unit:4,title:'Political Boundaries and Representation',stimulus:`<div class="box-info">A state has four districts of roughly equal population. After redistricting, voters from one party are concentrated into one district while the opposing party holds smaller majorities in the other three.</div>`,qs:[
      ['The redistricting strategy described is...',['Packing','Reapportionment','Devolution','Irredentism'],'Packing','Packing concentrates opposition voters into fewer districts.'],
      ['The most direct consequence is a change in...',['Political representation','Physiological density','Agricultural output','Cultural hearths'],'Political representation','District boundaries affect how votes translate into seats.'],
      ['Which process normally occurs before states gain or lose seats based on population change?',['Reapportionment','Syncretism','Suburbanization','Outsourcing'],'Reapportionment','Reapportionment reallocates seats before district lines are redrawn.']]},
    {unit:5,title:'Agricultural Location',stimulus:`<table class="simple-table"><tr><th>Farm product</th><th>Distance to market</th><th>Spoilage risk</th><th>Transport cost/kg</th></tr><tr><td>Leafy greens</td><td>25 km</td><td>High</td><td>High</td></tr><tr><td>Wheat</td><td>220 km</td><td>Low</td><td>Low</td></tr><tr><td>Cattle</td><td>340 km</td><td>Low</td><td>Medium</td></tr></table>`,qs:[
      ['Which model best explains the pattern?',['Von Thünen model','Burgess model','DTM','World-systems theory'],'Von Thünen model','Distance, perishability, and transport costs shape agricultural land use.'],
      ['Which innovation would most weaken the observed distance pattern?',['Refrigerated transportation','Higher spoilage','Higher transport costs','Less road access'],'Refrigerated transportation','Refrigeration lets perishable goods travel farther.'],
      ['Which product is most consistent with extensive agriculture?',['Cattle','Leafy greens','Greenhouse herbs','Market flowers'],'Cattle','Ranching typically uses large land areas with low inputs per unit of land.']]},
    {unit:6,title:'Urban Change',stimulus:`<table class="simple-table"><tr><th>Neighborhood</th><th>Median rent change</th><th>Transit access</th><th>College degree share change</th></tr><tr><td>A</td><td>+46%</td><td>High</td><td>+21 pts</td></tr><tr><td>B</td><td>+11%</td><td>Low</td><td>+3 pts</td></tr></table>`,qs:[
      ['Neighborhood A most likely shows evidence of...',['Gentrification','Counterurbanization','Agricultural intensification','Devolution'],'Gentrification','Rapid rent increases and socioeconomic change are common indicators.'],
      ['Which qualitative source would best complement the table?',['Interviews with longtime residents','A world climate map','National fertility data','A list of state capitals'],'Interviews with longtime residents','Interviews reveal lived experience and displacement pressures not visible in aggregate data.'],
      ['Which policy most directly helps preserve mixed-income housing?',['Inclusionary zoning','Blockbusting','Redlining','Urban sprawl'],'Inclusionary zoning','It can require or encourage affordable units in new development.']]},
    {unit:7,title:'Development and Global Production',stimulus:`<div class="box-info">A footwear company designs products in a high-income country, sources rubber from a lower-income country, manufactures in a special economic zone, and sells globally. The manufacturing region gains jobs but remains dependent on imported technology and foreign ownership.</div>`,qs:[
      ['The production pattern best illustrates...',['New international division of labor','Subsistence agriculture','Central place theory','Population momentum'],'New international division of labor','Production stages are separated across countries based on costs, skills, and firm strategy.'],
      ['Which theory most directly emphasizes unequal core-periphery relationships?',['World-systems theory','Rostow only','Von Thünen','Sector model'],'World-systems theory','World-systems theory focuses on unequal positions in the global economy.'],
      ['Which change would most likely increase local development benefits?',['Develop local suppliers and worker skills','Depend on one export only','Reduce education spending','Ban all infrastructure investment'],'Develop local suppliers and worker skills','Local linkages and human capital can increase multiplier effects and reduce dependency.']]}
  ];

  const frqs=[
    {unit:1,title:'Scale and Access',stimulus:'A regional map shows high overall access to grocery stores, but a neighborhood map reveals several low-income areas more than 2 miles from a full-service grocery store.',parts:[['A','Describe','one spatial pattern visible when the scale changes.','Local-scale analysis reveals clusters of low access that the regional average hides.'],['B','Explain','why scale of analysis changes the interpretation.','Aggregation at the regional scale masks neighborhood variation; therefore local analysis reveals unequal access.'],['C','Explain','one GIS layer that could help planners respond.','Transit routes, household income, or travel-time layers could identify underserved areas and guide store or transit placement.']]},
    {unit:2,title:'Aging and Migration',stimulus:'Country X has a TFR of 1.3, rising life expectancy, and a shrinking working-age population.',parts:[['A','Identify','one likely demographic consequence.','An aging population or higher elderly dependency ratio.'],['B','Explain','one economic challenge caused by the pattern.','A smaller workforce may support more retirees, increasing pension or health-care pressure.'],['C','Explain','one migration policy response and a possible tradeoff.','Working-age immigration can fill labor shortages, but rapid immigration may increase housing or integration pressures.']]},
    {unit:3,title:'Language and Identity',stimulus:'A multilingual country adopts one official language for schools and government while minority-language communities expand local-language media and schools.',parts:[['A','Identify','one centripetal effect of the official-language policy.','A shared official language can improve communication and strengthen national identity.'],['B','Explain','one centrifugal effect of the policy.','Minority groups may view the policy as cultural marginalization, increasing regional or ethnic tension.'],['C','Explain','how contemporary communication can support cultural divergence.','Digital media lets minority groups maintain and revive language networks across distance.']]},
    {unit:4,title:'Devolution',stimulus:'A wealthy peripheral region with a distinct language demands greater control over taxes and education.',parts:[['A','Identify','the political process.','Devolution.'],['B','Explain','one cultural and one economic factor encouraging the process.','Distinct language strengthens regional identity, while tax grievances create economic conflict with the central government.'],['C','Explain','how federalism might reduce separatist pressure.','Regional authority over education or taxation can address grievances while preserving the state.']]},
    {unit:5,title:'Food Systems',stimulus:'A dry agricultural region expands irrigation and high-yield crops. Output rises, but groundwater levels fall and fertilizer runoff increases.',parts:[['A','Identify','the agricultural change most associated with high-yield inputs.','The Green Revolution / Third Agricultural Revolution.'],['B','Explain','one benefit and one environmental cost.','Higher yields improve food supply, but irrigation can deplete groundwater and fertilizer can pollute waterways.'],['C','Explain','one sustainable response.','Drip irrigation, crop rotation, precision fertilizer, or drought-tolerant crops can reduce resource use while maintaining production.']]},
    {unit:6,title:'Urban Sustainability',stimulus:'A metropolitan area adopts a growth boundary, expands rail transit, and allows apartments above shops near stations.',parts:[['A','Identify','one planning strategy shown.','Smart growth, transit-oriented development, or mixed-use development.'],['B','Explain','how the policies could reduce sprawl.','Concentrating development near transit and existing infrastructure reduces pressure for low-density outward expansion.'],['C','Explain','one possible social tradeoff.','Higher demand near transit can raise land values and rents, potentially displacing lower-income residents without affordability policies.']]},
    {unit:7,title:'Globalization and Development',stimulus:'A lower-income country attracts electronics factories with tax incentives. Exports and jobs increase, but most high-value design work remains abroad.',parts:[['A','Identify','one development strategy shown.','Export-oriented industrialization / use of special economic zones or foreign direct investment.'],['B','Explain','how the pattern fits world-systems theory.','Higher-value functions remain concentrated in core economies while lower-wage manufacturing occurs in peripheral or semi-peripheral locations.'],['C','Explain','one strategy that could move the country toward higher-value activity.','Investing in education, infrastructure, research, and local supplier networks can build human capital and domestic value-added production.']]}
  ];

  let mode='mcq',setIndex=0,qIndex=0,selected=null,score=0,answered=0,frqIndex=0,frqAnswers={},frqReveal=false;
  const oldRender=render;
  render=function(){ if(active==='examLab'){renderNav();document.getElementById('app').innerHTML=examLabPage();return;} oldRender(); };

  function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  window.examLabMode=function(m){mode=m;selected=null;frqReveal=false;render();};
  window.examLabChoose=function(i){if(selected!==null)return;selected=i;answered++;const q=sets[setIndex].qs[qIndex];if(q[1][i]===q[2])score++;render();};
  window.examLabNext=function(){selected=null;qIndex++;if(qIndex>=sets[setIndex].qs.length){qIndex=0;setIndex=(setIndex+1)%sets.length;}render();};
  window.examLabSet=function(i){setIndex=Number(i);qIndex=0;selected=null;render();};
  window.examLabFrq=function(i){frqIndex=Number(i);frqAnswers={};frqReveal=false;render();};
  window.examLabAnswer=function(i,v){frqAnswers[i]=v;};
  window.examLabReveal=function(){frqReveal=true;render();};

  function examLabPage(){return `<main class="wrap"><section class="card"><h2>🧪 AP Exam Lab</h2><p>Practice with original stimulus-based questions. The goal is to read evidence, choose the geographic concept, and explain the relationship — the same habits the AP exam rewards.</p><div class="button-row"><button class="${mode==='mcq'?'btn-primary':'btn-secondary'}" onclick="examLabMode('mcq')">Stimulus MCQ</button><button class="${mode==='frq'?'btn-primary':'btn-secondary'}" onclick="examLabMode('frq')">Mini FRQ</button></div></section>${mode==='mcq'?mcqPage():frqPage()}</main>`;}
  function mcqPage(){const s=sets[setIndex],q=s.qs[qIndex];return `<section class="card"><div class="mastery-mini-nav"><span class="pill">Unit ${s.unit}</span><span>${answered?`Session score: ${score}/${answered}`:'Start a session'}</span></div><h3>${s.title}</h3><div class="box-info">${s.stimulus}</div><p><b>Question ${qIndex+1} of ${s.qs.length}:</b> ${q[0]}</p><div class="quiz-options">${q[1].map((o,i)=>{const chosen=selected===i,correct=selected!==null&&o===q[2];return `<button class="quiz-option ${correct?'correct':chosen?'wrong':''}" onclick="examLabChoose(${i})" ${selected!==null?'disabled':''}>${String.fromCharCode(65+i)}. ${o}</button>`}).join('')}</div>${selected!==null?`<div class="${q[1][selected]===q[2]?'box-good':'box-warn'}"><b>${q[1][selected]===q[2]?'Correct':'Not quite'}</b><p>${q[3]}</p></div><button class="btn-primary" onclick="examLabNext()">Next question →</button>`:''}<hr><label><b>Jump to unit:</b> <select onchange="examLabSet(this.value)">${sets.map((x,i)=>`<option value="${i}" ${i===setIndex?'selected':''}>Unit ${x.unit}: ${x.title}</option>`).join('')}</select></label></section>`;}
  function frqPage(){const f=frqs[frqIndex];return `<section class="card"><div class="mastery-mini-nav"><span class="pill">Unit ${f.unit}</span><select onchange="examLabFrq(this.value)">${frqs.map((x,i)=>`<option value="${i}" ${i===frqIndex?'selected':''}>Unit ${x.unit}: ${x.title}</option>`).join('')}</select></div><h3>${f.title}</h3><div class="box-info">${f.stimulus}</div><p class="muted">Write concise AP-style responses. For Explain, show a clear causal link — not just a definition.</p>${f.parts.map((p,i)=>`<div class="rubric-row"><b>${p[0]}. ${p[1]}:</b> ${p[2]}<textarea class="answer-textarea" placeholder="Write part ${p[0]}..." oninput="examLabAnswer(${i},this.value)">${esc(frqAnswers[i]||'')}</textarea>${frqReveal?`<div class="box-good"><b>Model point:</b> ${p[3]}</div>`:''}</div>`).join('')}<button class="btn-primary" onclick="examLabReveal()">Show model points</button>${frqReveal?'<p class="box-warn"><b>Self-check:</b> Did your response answer the exact command verb, use geographic vocabulary, and explain cause/effect where required? Revise before moving on.</p>':''}</section>`;}
})();
