// PR #6: Practice & Mastery engine — randomized tests, readiness by CED topic, missed review, cumulative practice.
(function(){
  if(window.__practiceMasteryInstalled || typeof tabs==='undefined' || typeof render==='undefined') return;
  window.__practiceMasteryInstalled=true;
  const idx=Math.max(1,tabs.findIndex(t=>t[0]==='examLab')); tabs.splice(idx,0,['practiceMastery','🎯 Practice & Mastery']);
  const core=[
[1,'1.1','A map shades counties by percent of adults with a college degree. Which map type is used?',['Choropleth','Dot-density','Reference','Isoline'],'Choropleth','Defined areas are shaded by a rate or percentage.'],[1,'1.2','Which source is best for tracking forest-cover change over a large region across 20 years?',['Remote sensing','A single interview','A mental map','A road atlas'],'Remote sensing','Satellite imagery allows repeated observation across large areas.'],[1,'1.4','Two large nearby cities have stronger interaction than two small distant cities. Which concept best explains this?',['Gravity model','Environmental determinism','Formal region','Cartogram'],'Gravity model','Interaction increases with population size and decreases with distance.'],[2,'2.1','Which density measure best shows pressure of people on farmland?',['Physiological density','Arithmetic density','Agricultural density','Population momentum'],'Physiological density','It divides total population by arable land.'],[2,'2.5','Why is population growth often fastest in DTM Stage 2?',['Death rates fall before birth rates','Birth and death rates are both low','Migration stops','Fertility falls below replacement'],'Death rates fall before birth rates','This creates a large gap between births and deaths.'],[3,'3.2','A fashion trend spreads first from celebrities to major cities. Which diffusion type is this?',['Hierarchical','Contagious','Relocation','Stimulus'],'Hierarchical','The trait spreads through influential people and high-order places.'],[4,'4.6','Concentrating opposition voters into one district is called...',['Packing','Cracking','Reapportionment','Devolution'],'Packing','Packing concentrates a group into fewer districts.'],[5,'5.6','In the Von Thünen model, dairy is close to market mainly because...',['It is perishable and costly to transport','Land is cheapest there','It requires no labor','It is always subsistence farming'],'It is perishable and costly to transport','Perishability and transportation costs favor locations near the market.'],[6,'6.10','Investment raises rents and displaces longtime residents. This is...',['Gentrification','Suburbanization','Counterurbanization','Filtering only'],'Gentrification','Neighborhood reinvestment can raise costs and cause displacement.'],[7,'7.3','World-systems theory emphasizes...',['Core-periphery inequality','A universal linear path to development','Agricultural land rings','Urban hierarchy'],'Core-periphery inequality','It focuses on unequal relationships in the global economy.']
  ].map((q,i)=>({id:'pm'+(i+1),unit:q[0],topic:q[1],prompt:q[2],choices:q[3],answer:q[4],explain:q[5]}));

  // Quality-first bank. The old mass-generated bank remains in the repo as drafting inventory,
  // but is intentionally NOT served because some stems reveal the answer by name.
  const setQuestions=[...(window.APHG_STIMULUS_SET_QUESTIONS||[]),...(window.APHG_STIMULUS_SET_QUESTIONS_EXTRA||[]),...(window.APHG_REAL_DATA_QUESTIONS||[])];
  const cedBase=(typeof quiz!=='undefined'?quiz:[]).map((q,i)=>({id:`pm-ced-${i+1}`,unit:Number(String(q[0]||'').match(/\d+/)?.[0]||0),topic:String(q.topic||window.APHGTopicSkillMastery?.topicFromQuestion(q)||''),prompt:q[1],choices:q[2],answer:q[3],explain:q[4],skill:q.skill,difficulty:q.difficulty,misconception:q.misconception})).filter(q=>q.unit&&q.topic&&q.prompt&&q.choices?.length===4&&q.answer);
  const unique=new Map();[...core,...(window.APHG_IMAGE_MCQ_BANK||[]),...cedBase].forEach(q=>{if(!unique.has(q.prompt))unique.set(q.prompt,q);});
  const nonSetBase=[...unique.values()];
  const apFrames=[p=>p,p=>`Choose the best answer. ${p}`,p=>`Use AP Human Geography reasoning. ${p}`];
  function variantize(q){return apFrames.map((f,i)=>({...q,id:`${q.id}-v${i+1}`,prompt:f(q.prompt),variant:i+1}));}
  const variants=nonSetBase.flatMap(variantize);
  const bank=variants.concat(setQuestions);
  const allSets=[...(window.APHG_STIMULUS_SETS||[]),...(window.APHG_STIMULUS_SETS_EXTRA||[]),...(window.APHG_REAL_DATA_SETS||[])];
  const storeKey='aphgPracticeMasteryV4'; const seenKey='aphgPracticeRecentSeenV2'; let state={mode:'dashboard',unit:1,deck:[],index:0,selected:null,session:[]};
  function load(){try{return JSON.parse(localStorage.getItem(storeKey)||'{}')}catch(e){return {}}} function save(p){localStorage.setItem(storeKey,JSON.stringify(p));}
  function loadSeen(){try{return JSON.parse(localStorage.getItem(seenKey)||'{}')}catch(e){return {}}} function saveSeen(x){localStorage.setItem(seenKey,JSON.stringify(x));}
  function record(q,correct){const p=load(),x=p[q.topic]||{right:0,total:0,missed:[],recent:[],days:[],streak:0};x.total++;if(correct)x.right++;else if(!x.missed.includes(q.id))x.missed.push(q.id);if(correct)x.missed=x.missed.filter(id=>id!==q.id);x.recent=(x.recent||[]).concat(correct?1:0).slice(-8);x.streak=correct?(x.streak||0)+1:0;const day=new Date().toISOString().slice(0,10);x.days=x.days||[];if(!x.days.includes(day))x.days.push(day);x.days=x.days.slice(-12);p[q.topic]=x;save(p);try{window.APHGTopicSkillMastery?.recordEvidence(q,correct);}catch(e){}}
  function score(t){const x=load()[t];if(!x||!x.total)return null;const recent=x.recent||[];const pct=Math.round(recent.reduce((a,b)=>a+b,0)/recent.length*100);return {pct,attempts:x.total,days:(x.days||[]).length,mastered:x.total>=5&&recent.length>=5&&pct>=80&&(x.days||[]).length>=2&&(x.streak||0)>=2};}
  function shuffle(a){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
  function keyFor(mode,unit){return mode==='unit'?`unit-${unit}`:mode;}
  function setToQuestions(set){return set.questions.map((q,i)=>{const saved=setQuestions.find(x=>x.setId===set.id&&x.setIndex===i);return {id:saved?.id||`set-${set.id}-${i+1}`,unit:set.unit,topic:q[4],prompt:q[0],choices:q[1],answer:q[2],explain:q[3],stimulus:set.stimulus,stimulusTitle:set.title,setId:set.id,setIndex:i,setSize:set.questions.length,authentic:/^real-/.test(set.id)};});}
  function chooseSets(mode,unit){let candidates=allSets;if(mode==='unit'||mode==='quick')candidates=allSets.filter(s=>s.unit===unit);if(!candidates.length)return [];return shuffle(candidates).slice(0,mode==='cumulative'?2:1);}
  function buildDeck(mode,unit){
    if(mode==='missed'){const p=load(),ids=new Set(Object.values(p).flatMap(x=>x.missed||[]));return shuffle(bank.filter(q=>ids.has(q.id))).slice(0,30).map(q=>({...q,choices:shuffle(q.choices)}));}
    let pool=variants;if(mode==='unit'||mode==='quick')pool=variants.filter(q=>q.unit===unit);
    const count=mode==='quick'?5:mode==='unit'?25:30,seen=loadSeen(),k=keyFor(mode,unit),recent=new Set(seen[k]||[]);let fresh=pool.filter(q=>!recent.has(q.id));if(fresh.length<count)fresh=pool;
    const selectedSets=chooseSets(mode,unit);const grouped=selectedSets.flatMap(setToQuestions);const fillCount=Math.max(0,count-grouped.length);
    const filler=shuffle(fresh).slice(0,fillCount);let picked=[...grouped,...filler].map(q=>({...q,choices:shuffle(q.choices)}));
    // Keep each stimulus set together, but move the set block to a different place each session.
    if(grouped.length&&filler.length){const block=grouped.map(q=>({...q,choices:shuffle(q.choices)}));const rest=picked.slice(grouped.length);const insertAt=Math.floor(Math.random()*(rest.length+1));picked=[...rest.slice(0,insertAt),...block,...rest.slice(insertAt)];}
    seen[k]=picked.filter(q=>!q.setId).map(q=>q.id).slice(-80);saveSeen(seen);return picked;
  }
  function start(mode,unit){state={mode:'session',unit:unit||1,deck:buildDeck(mode,unit||1),index:0,selected:null,session:[],showHelp:false};render();}
  window.pmStart=start;window.pmChoose=i=>{if(state.selected!==null)return;const q=state.deck[state.index];state.selected=i;const ok=q.choices[i]===q.answer;record(q,ok);state.session.push({q,correct:ok});render();};window.pmNext=()=>{state.index++;state.selected=null;state.showHelp=false;if(state.index>=state.deck.length)state.mode='results';render();};window.pmHelp=()=>{state.showHelp=true;render();};window.pmSetUnit=u=>{state.unit=Number(u)||1;render();};window.pmDashboard=()=>{state.mode='dashboard';render();};window.pmReset=()=>{if(confirm('Reset Practice & Mastery progress?')){localStorage.removeItem(storeKey);localStorage.removeItem(seenKey);state.mode='dashboard';render();}};
  const oldRender=render;render=function(){if(active==='practiceMastery'){renderNav();document.getElementById('app').innerHTML=page();return;}oldRender();};
  function page(){return `<main class="wrap">${state.mode==='dashboard'?dash():state.mode==='session'?session():results()}</main>`;}
  function topicStatus(s){if(!s)return 'Not practiced yet';if(s.mastered)return 'Ready ✓';if(s.attempts<5)return `Keep practicing · ${5-s.attempts} more attempt${5-s.attempts===1?'':'s'} needed`;if(s.pct>=80&&s.days<2)return 'Come back another day to prove it';return s.pct>=80?'Almost ready — get two correct in a row':'Keep practicing';}
  function dash(){
    const topics=[...new Set(bank.filter(q=>Number(q.unit)===state.unit).map(q=>q.topic))],stats=topics.map(t=>[t,score(t)]),attempted=stats.filter(x=>x[1]),mastered=stats.filter(x=>x[1]?.mastered),p=load(),missed=Object.values(p).reduce((n,x)=>n+(x.missed||[]).length,0);
    const next=missed?`<button class="btn-primary" onclick="pmStart('missed')">Review My Mistakes</button>`:`<button class="btn-primary" onclick="pmStart('quick',${state.unit})">Start 5-Minute Practice</button>`;
    return `<section class="card"><h2>🎯 What should I do next?</h2><p>${missed?'Start with questions you missed. Read the explanation, then try each idea again.':'Choose the unit you are learning and complete five questions. We will show you what to review next.'}</p><div class="button-row">${next}<label class="pill">Unit <select onchange="pmSetUnit(this.value)">${[1,2,3,4,5,6,7].map(u=>`<option value="${u}" ${u===state.unit?'selected':''}>${u}</option>`).join('')}</select></label></div></section>
    <section class="card"><h2>Your Progress</h2><p>Progress is saved on this device. “Ready” means at least 80% correct after five or more attempts.</p><div class="readiness-grid"><div class="readiness-tile"><b>${mastered.length}/${topics.length}</b><span>ready</span></div><div class="readiness-tile"><b>${attempted.length}</b><span>practiced</span></div><div class="readiness-tile"><b>${missed}</b><span>mistakes to review</span></div></div></section>
    <section class="card"><h3>More Practice</h3><p>Use these when you want a longer challenge.</p><div class="button-row">${[1,2,3,4,5,6,7].map(u=>`<button class="btn-secondary" onclick="pmStart('unit',${u})">Unit ${u} Check · 25</button>`).join('')}<button class="btn-secondary" onclick="pmStart('cumulative')">Mixed Exam Practice · 30</button><button class="btn-secondary" onclick="pmStart('missed')" ${missed?'':'disabled'}>Review My Mistakes</button><button class="btn-secondary" onclick="pmReset()">Reset Progress</button></div></section>
    <section class="card"><h3>Progress by Topic</h3><div class="readiness-grid">${stats.map(([t,s])=>`<div class="readiness-tile"><b>${s?s.pct+'%':'—'}</b><span>Topic ${t} · ${topicStatus(s)}</span></div>`).join('')}</div></section>`;
  }
  function session(){
    if(!state.deck.length)return `<section class="card"><h2>No questions are ready yet</h2><p>Choose another unit or return to your progress page.</p><button class="btn-primary" onclick="pmDashboard()">Back</button></section>`;
    const q=state.deck[state.index],sel=state.selected,media=q.stimulus||q.visual,wrong=sel!==null&&q.choices[sel]!==q.answer,confuser=wrong?q.choices[sel]:'';
    return `<section class="card"><div class="mastery-mini-nav"><span class="pill">Unit ${q.unit} · Topic ${q.topic}</span><span>${state.index+1}/${state.deck.length}</span></div>${q.setId?`<div class="box-yellow"><b>Use this source:</b> ${q.stimulusTitle||'Visual evidence'} · Question ${q.setIndex+1} of ${q.setSize}. Keep using the same source for this set.</div>`:''}${media?`<div class="box-info" style="margin:12px 0">${media}</div>`:''}<h2>${q.prompt}</h2><div class="quiz-options">${q.choices.map((choice,i)=>`<button class="quiz-option ${sel!==null&&choice===q.answer?'correct':sel===i&&choice!==q.answer?'wrong':''}" onclick="pmChoose(${i})" ${sel!==null?'disabled':''}>${String.fromCharCode(65+i)}. ${choice}</button>`).join('')}</div>${sel!==null?`<div class="${wrong?'box-warn':'box-good'}"><b>${wrong?'Not yet — this is how you improve.':'Correct!'}</b><p>${q.explain}</p></div>${wrong?`<button class="btn-secondary" onclick="pmHelp()">Review This Topic</button>`:''}${state.showHelp?`<div class="box-info"><h3>Topic ${q.topic} in plain language</h3><p><b>Correct idea:</b> ${q.answer}</p><p><b>What it means here:</b> ${q.explain}</p><p><b>Watch out:</b> ${confuser} does not fit the evidence in this question. Explain why before moving on.</p></div>`:''}<button class="btn-primary" onclick="pmNext()">${state.index+1===state.deck.length?'See My Results':'Next →'}</button>`:''}</section>`;
  }
  function results(){
    const right=state.session.filter(x=>x.correct).length,total=state.session.length,pct=total?Math.round(right/total*100):0,weak=[...new Set(state.session.filter(x=>!x.correct).map(x=>x.q.topic))];
    return `<section class="card"><h2>You finished!</h2><div class="readiness-grid"><div class="readiness-tile"><b>${right}/${total}</b><span>correct</span></div><div class="readiness-tile"><b>${pct}%</b><span>this practice</span></div><div class="readiness-tile"><b>${weak.length}</b><span>topics to revisit</span></div></div>${weak.length?`<div class="box-warn"><b>Practice next:</b> Topics ${weak.join(', ')}. Review the explanation before trying again.</div>`:`<div class="box-good"><b>Strong work.</b> Come back later so the ideas stay fresh.</div>`}<div class="button-row"><button class="btn-primary" onclick="pmDashboard()">Back to My Progress</button><button class="btn-secondary" onclick="pmStart('missed')" ${weak.length?'':'disabled'}>Review My Mistakes</button><button class="btn-secondary" onclick="pmStart('quick',${state.unit})">Another 5 Questions</button></div></section>`;
  }
})();
