// PR #6: Practice & Mastery engine — randomized tests, readiness by CED topic, missed review, cumulative practice.
(function(){
  if(window.__practiceMasteryInstalled || typeof tabs==='undefined' || typeof render==='undefined') return;
  window.__practiceMasteryInstalled=true;
  const idx=Math.max(1,tabs.findIndex(t=>t[0]==='examLab'));
  tabs.splice(idx,0,['practiceMastery','🎯 Practice & Mastery']);

  const bank=[
    // Unit 1
    [1,'1.1','A map shades counties by percent of adults with a college degree. Which map type is used?',['Choropleth','Dot-density','Reference','Isoline'],'Choropleth','Defined areas are shaded by a rate or percentage.'],
    [1,'1.2','Which source is best for tracking forest-cover change over a large region across 20 years?',['Remote sensing','A single interview','A mental map','A road atlas'],'Remote sensing','Satellite imagery allows repeated observation across large areas.'],
    [1,'1.4','Two large nearby cities have stronger interaction than two small distant cities. Which concept best explains this?',['Gravity model','Environmental determinism','Formal region','Cartogram'],'Gravity model','Interaction increases with population size and decreases with distance.'],
    [1,'1.6','A national average hides strong neighborhood differences. Which geographic issue is most important?',['Scale of analysis','Relocation diffusion','Sovereignty','Carrying capacity'],'Scale of analysis','Aggregation can hide local variation.'],
    [1,'1.7','A radio station’s broadcast area is best classified as which type of region?',['Functional','Formal','Perceptual','Political'],'Functional','A functional region is organized around a node and interactions.'],
    // Unit 2
    [2,'2.1','Which density measure best shows pressure of people on farmland?',['Physiological density','Arithmetic density','Agricultural density','Population momentum'],'Physiological density','It divides total population by arable land.'],
    [2,'2.3','A population pyramid with a very wide base most strongly suggests...',['A youthful population','An aging population','Very low fertility','Negative momentum'],'A youthful population','Large young cohorts create a wide base.'],
    [2,'2.5','Why is population growth often fastest in DTM Stage 2?',['Death rates fall before birth rates','Birth and death rates are both low','Migration stops','Fertility falls below replacement'],'Death rates fall before birth rates','This creates a large gap between births and deaths.'],
    [2,'2.8','Which change most often contributes to lower fertility?',['Greater female education and employment','Higher infant mortality','Lower urbanization','Reduced access to health care'],'Greater female education and employment','Education and work opportunities often delay marriage and childbearing.'],
    [2,'2.10','A person fleeing war crosses an international border and receives protection. Which term best fits?',['Refugee','IDP','Guest worker','Step migrant'],'Refugee','Refugees cross an international border due to danger or persecution.'],
    // Unit 3
    [3,'3.2','A fashion trend spreads first from celebrities to major cities. Which diffusion type is this?',['Hierarchical','Contagious','Relocation','Stimulus'],'Hierarchical','The trait spreads through influential people and high-order places.'],
    [3,'3.2','Migrants carry a religion to a new country. Which diffusion type is this?',['Relocation','Contagious','Hierarchical','Reverse hierarchical'],'Relocation','People move and bring the cultural trait with them.'],
    [3,'3.3','A global restaurant changes its menu to fit local religious food rules. Which process is shown?',['Stimulus diffusion','Assimilation','Acculturation only','Distance decay'],'Stimulus diffusion','The core idea spreads but changes to fit local culture.'],
    [3,'3.4','Which term describes the visible imprint of culture on the built environment?',['Cultural landscape','Placelessness','Nation-state','Territoriality'],'Cultural landscape','Buildings, signs, land use, and sacred spaces reflect culture.'],
    [3,'3.7','A language used by speakers of different native languages for trade is a...',['Lingua franca','Dialect','Pidgin only','Toponym'],'Lingua franca','It provides a shared language for communication.'],
    // Unit 4
    [4,'4.1','Which term means a political unit with sovereignty over territory and population?',['State','Nation','Nation-state only','Region'],'State','A state has territory, population, government, and sovereignty.'],
    [4,'4.2','A culturally unified people without their own sovereign state are a...',['Stateless nation','Multinational state','Federal state','Supranational organization'],'Stateless nation','A nation may exist without controlling a sovereign state.'],
    [4,'4.4','Which boundary was imposed by outside powers with little regard for local cultural patterns?',['Superimposed','Antecedent','Relic','Subsequent'],'Superimposed','Such boundaries are placed over existing cultural landscapes.'],
    [4,'4.6','Concentrating opposition voters into one district is called...',['Packing','Cracking','Reapportionment','Devolution'],'Packing','Packing concentrates a group into fewer districts.'],
    [4,'4.8','A region gaining more power from the central government illustrates...',['Devolution','Imperialism','Reapportionment','Balkanization only'],'Devolution','Power shifts from the central government to regions.'],
    // Unit 5
    [5,'5.1','The shift from hunting and gathering to settled farming is the...',['First Agricultural Revolution','Second Agricultural Revolution','Green Revolution','Industrial Revolution'],'First Agricultural Revolution','Domestication made permanent agriculture possible.'],
    [5,'5.4','Which system uses large land areas and low inputs per unit of land?',['Extensive agriculture','Intensive agriculture','Plantation agriculture only','Market gardening'],'Extensive agriculture','Ranching and similar systems use large areas with lower inputs per acre.'],
    [5,'5.6','In the Von Thünen model, dairy is close to market mainly because...',['It is perishable and costly to transport','Land is cheapest there','It requires no labor','It is always subsistence farming'],'It is perishable and costly to transport','Perishability and transportation costs favor locations near the market.'],
    [5,'5.9','Which change is most associated with the Green Revolution?',['High-yield seeds, irrigation, and fertilizer','A return to hunting and gathering','Less mechanization','Elimination of commercial farming'],'High-yield seeds, irrigation, and fertilizer','These inputs sharply increased yields.'],
    [5,'5.12','Which practice best supports sustainable agriculture?',['Crop rotation and efficient irrigation','Continuous monoculture only','Overgrazing','Removing all fallow periods'],'Crop rotation and efficient irrigation','These practices can preserve soil and water while maintaining production.'],
    // Unit 6
    [6,'6.1','A city with global influence in finance, culture, and business is a...',['World city','Primate city only','Edge city','Squatter settlement'],'World city','World cities are major nodes in global networks.'],
    [6,'6.3','Central place theory is mainly concerned with...',['Settlement size, spacing, and services','Agricultural rings','Population transition','Political boundaries'],'Settlement size, spacing, and services','The theory explains market areas, thresholds, and ranges.'],
    [6,'6.5','Which urban model shows wedge-shaped sectors extending from the CBD?',['Sector model','Concentric zone','Multiple nuclei','Latin American model only'],'Sector model','Land uses extend outward in sectors, often along transport routes.'],
    [6,'6.10','Investment raises rents and displaces longtime residents. This is...',['Gentrification','Suburbanization','Counterurbanization','Filtering only'],'Gentrification','Neighborhood reinvestment can raise costs and cause displacement.'],
    [6,'6.11','Which policy is most consistent with smart growth?',['Mixed-use development near transit','Low-density expansion at the fringe','More parking-only zoning','Separating all land uses'],'Mixed-use development near transit','Smart growth favors compact, walkable, transit-oriented development.'],
    // Unit 7
    [7,'7.2','Which measure combines income, education, and life expectancy?',['HDI','GDP','GNI only','GII'],'HDI','The Human Development Index combines three development dimensions.'],
    [7,'7.3','World-systems theory emphasizes...',['Core-periphery inequality','A universal linear path to development','Agricultural land rings','Urban hierarchy'],'Core-periphery inequality','It focuses on unequal relationships in the global economy.'],
    [7,'7.4','A firm moves assembly to a lower-wage country while design stays in a high-income country. This illustrates...',['New international division of labor','Subsistence agriculture','Rank-size rule','Population momentum'],'New international division of labor','Production stages are separated globally according to costs and skills.'],
    [7,'7.5','Factories cluster near one another to share suppliers and labor. This is...',['Agglomeration','Deindustrialization','Outsourcing only','Distance decay'],'Agglomeration','Clustering creates shared economic advantages.'],
    [7,'7.8','Which strategy best supports sustainable development?',['Investing in education, health, and renewable infrastructure','Relying on one export commodity','Ignoring environmental costs','Reducing human capital'],'Investing in education, health, and renewable infrastructure','Sustainable development balances economic, social, and environmental needs.']
  ].map((q,i)=>({id:'pm'+(i+1),unit:q[0],topic:q[1],prompt:q[2],choices:q[3],answer:q[4],explain:q[5]}));

  const storeKey='aphgPracticeMasteryV1';
  let state={mode:'dashboard',unit:1,deck:[],index:0,selected:null,session:[],reviewOnly:false};
  function loadProgress(){try{return JSON.parse(localStorage.getItem(storeKey)||'{}')}catch(e){return {}}}
  function saveProgress(p){localStorage.setItem(storeKey,JSON.stringify(p));}
  function record(q,correct){const p=loadProgress(); const x=p[q.topic]||{right:0,total:0,missed:[]}; x.total++; if(correct)x.right++; else if(!x.missed.includes(q.id))x.missed.push(q.id); if(correct)x.missed=x.missed.filter(id=>id!==q.id); p[q.topic]=x; saveProgress(p);}
  function readiness(topic){const x=loadProgress()[topic]; return !x||!x.total?null:Math.round(x.right/x.total*100);}
  function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
  function start(mode,unit){state.mode='session';state.unit=unit||1;state.index=0;state.selected=null;state.session=[];state.reviewOnly=mode==='missed'; let pool=bank;if(mode==='unit')pool=bank.filter(q=>q.unit===unit);if(mode==='missed'){const p=loadProgress(),ids=new Set(Object.values(p).flatMap(x=>x.missed||[]));pool=bank.filter(q=>ids.has(q.id));}if(mode==='cumulative')pool=bank;state.deck=shuffle(pool).slice(0,mode==='unit'?Math.min(15,pool.length):Math.min(20,pool.length));render();}
  window.pmStart=start; window.pmChoose=function(i){if(state.selected!==null)return; const q=state.deck[state.index];state.selected=i;const correct=q.choices[i]===q.answer;record(q,correct);state.session.push({q,correct});render();}; window.pmNext=function(){state.index++;state.selected=null;if(state.index>=state.deck.length){state.mode='results';}render();}; window.pmDashboard=function(){state.mode='dashboard';render();}; window.pmReset=function(){if(confirm('Reset Practice & Mastery progress?')){localStorage.removeItem(storeKey);state.mode='dashboard';render();}};

  const oldRender=render;
  render=function(){if(active==='practiceMastery'){renderNav();document.getElementById('app').innerHTML=page();return;}oldRender();};
  function page(){return `<main class="wrap">${state.mode==='dashboard'?dashboard():state.mode==='session'?session():results()}</main>`;}
  function dashboard(){const p=loadProgress();const topics=[...new Set(bank.map(q=>q.topic))];const attempted=topics.filter(t=>readiness(t)!==null);const avg=attempted.length?Math.round(attempted.reduce((s,t)=>s+readiness(t),0)/attempted.length):0;const missed=Object.values(p).reduce((n,x)=>n+(x.missed||[]).length,0);return `<section class="card"><h2>🎯 Practice & Mastery</h2><p>Use randomized tests to build durable APHG knowledge. Readiness is based on your own question history by CED topic.</p><div class="readiness-grid"><div class="readiness-tile"><b>${avg}%</b><span>average readiness</span></div><div class="readiness-tile"><b>${attempted.length}</b><span>topics attempted</span></div><div class="readiness-tile"><b>${missed}</b><span>questions to review</span></div></div><div class="button-row">${[1,2,3,4,5,6,7].map(u=>`<button class="btn-secondary" onclick="pmStart('unit',${u})">Unit ${u} Test</button>`).join('')}<button class="btn-primary" onclick="pmStart('cumulative')">Cumulative Practice</button><button class="btn-secondary" onclick="pmStart('missed')" ${missed?'':'disabled'}>Review Missed</button><button class="btn-secondary" onclick="pmReset()">Reset Progress</button></div></section><section class="card"><h3>CED Topic Readiness</h3><div class="readiness-grid">${topics.map(t=>{const r=readiness(t);return `<div class="readiness-tile"><b>${r===null?'—':r+'%'}</b><span>${t}</span></div>`}).join('')}</div><p class="muted">Aim for repeated 80%+ performance before calling a topic mastered. One correct answer is not enough evidence.</p></section>`;}
  function session(){if(!state.deck.length)return `<section class="card"><h2>No missed questions yet</h2><p>Complete some unit or cumulative practice first.</p><button class="btn-primary" onclick="pmDashboard()">Back to dashboard</button></section>`;const q=state.deck[state.index],sel=state.selected;return `<section class="card"><div class="mastery-mini-nav"><span class="pill">Unit ${q.unit} · Topic ${q.topic}</span><span>${state.index+1}/${state.deck.length}</span></div><h2>${q.prompt}</h2><div class="quiz-options">${q.choices.map((c,i)=>`<button class="quiz-option ${sel!==null&&c===q.answer?'correct':sel===i&&c!==q.answer?'wrong':''}" onclick="pmChoose(${i})" ${sel!==null?'disabled':''}>${String.fromCharCode(65+i)}. ${c}</button>`).join('')}</div>${sel!==null?`<div class="${q.choices[sel]===q.answer?'box-good':'box-warn'}"><b>${q.choices[sel]===q.answer?'Correct':'Not yet'}</b><p>${q.explain}</p></div><button class="btn-primary" onclick="pmNext()">${state.index+1===state.deck.length?'See results':'Next question →'}</button>`:''}</section>`;}
  function results(){const right=state.session.filter(x=>x.correct).length,total=state.session.length,pct=total?Math.round(right/total*100):0;const weak=[...new Set(state.session.filter(x=>!x.correct).map(x=>x.q.topic))];return `<section class="card"><h2>Practice Results</h2><div class="readiness-grid"><div class="readiness-tile"><b>${right}/${total}</b><span>correct</span></div><div class="readiness-tile"><b>${pct}%</b><span>session score</span></div><div class="readiness-tile"><b>${weak.length}</b><span>topics to revisit</span></div></div>${weak.length?`<div class="box-warn"><b>Revisit these CED topics:</b> ${weak.join(', ')}</div>`:`<div class="box-good"><b>Strong session.</b> Keep using cumulative practice so the material stays retrievable.</div>`}<div class="button-row"><button class="btn-primary" onclick="pmDashboard()">Back to Mastery Dashboard</button><button class="btn-secondary" onclick="pmStart('missed')">Review Missed</button></div></section>`;}
})();
