// PR #6: Practice & Mastery engine — randomized tests, readiness by CED topic, missed review, cumulative practice.
(function(){
  if(window.__practiceMasteryInstalled || typeof tabs==='undefined' || typeof render==='undefined') return;
  window.__practiceMasteryInstalled=true;
  const idx=Math.max(1,tabs.findIndex(t=>t[0]==='examLab')); tabs.splice(idx,0,['practiceMastery','🎯 Practice & Mastery']);
  const core=[
[1,'1.1','A map shades counties by percent of adults with a college degree. Which map type is used?',['Choropleth','Dot-density','Reference','Isoline'],'Choropleth','Defined areas are shaded by a rate or percentage.'],[1,'1.2','Which source is best for tracking forest-cover change over a large region across 20 years?',['Remote sensing','A single interview','A mental map','A road atlas'],'Remote sensing','Satellite imagery allows repeated observation across large areas.'],[1,'1.4','Two large nearby cities have stronger interaction than two small distant cities. Which concept best explains this?',['Gravity model','Environmental determinism','Formal region','Cartogram'],'Gravity model','Interaction increases with population size and decreases with distance.'],[2,'2.1','Which density measure best shows pressure of people on farmland?',['Physiological density','Arithmetic density','Agricultural density','Population momentum'],'Physiological density','It divides total population by arable land.'],[2,'2.5','Why is population growth often fastest in DTM Stage 2?',['Death rates fall before birth rates','Birth and death rates are both low','Migration stops','Fertility falls below replacement'],'Death rates fall before birth rates','This creates a large gap between births and deaths.'],[3,'3.2','A fashion trend spreads first from celebrities to major cities. Which diffusion type is this?',['Hierarchical','Contagious','Relocation','Stimulus'],'Hierarchical','The trait spreads through influential people and high-order places.'],[4,'4.6','Concentrating opposition voters into one district is called...',['Packing','Cracking','Reapportionment','Devolution'],'Packing','Packing concentrates a group into fewer districts.'],[5,'5.6','In the Von Thünen model, dairy is close to market mainly because...',['It is perishable and costly to transport','Land is cheapest there','It requires no labor','It is always subsistence farming'],'It is perishable and costly to transport','Perishability and transportation costs favor locations near the market.'],[6,'6.10','Investment raises rents and displaces longtime residents. This is...',['Gentrification','Suburbanization','Counterurbanization','Filtering only'],'Gentrification','Neighborhood reinvestment can raise costs and cause displacement.'],[7,'7.3','World-systems theory emphasizes...',['Core-periphery inequality','A universal linear path to development','Agricultural land rings','Urban hierarchy'],'Core-periphery inequality','It focuses on unequal relationships in the global economy.']
  ].map((q,i)=>({id:'pm'+(i+1),unit:q[0],topic:q[1],prompt:q[2],choices:q[3],answer:q[4],explain:q[5]}));
  const bank=core.concat(window.APHG_EXPANDED_BANK||[]);
  const storeKey='aphgPracticeMasteryV3';
  const seenKey='aphgPracticeRecentSeenV1';
  let state={mode:'dashboard',unit:1,deck:[],index:0,selected:null,session:[]};
  function load(){try{return JSON.parse(localStorage.getItem(storeKey)||'{}')}catch(e){return {}}}
  function save(p){localStorage.setItem(storeKey,JSON.stringify(p));}
  function loadSeen(){try{return JSON.parse(localStorage.getItem(seenKey)||'{}')}catch(e){return {}}}
  function saveSeen(x){localStorage.setItem(seenKey,JSON.stringify(x));}
  function record(q,correct){const p=load(),x=p[q.topic]||{right:0,total:0,missed:[],recent:[]};x.total++;if(correct)x.right++;else if(!x.missed.includes(q.id))x.missed.push(q.id);if(correct)x.missed=x.missed.filter(id=>id!==q.id);x.recent=(x.recent||[]).concat(correct?1:0).slice(-8);p[q.topic]=x;save(p);}
  function score(t){const x=load()[t];if(!x||!x.total)return null;const recent=x.recent||[];const pct=Math.round(recent.reduce((a,b)=>a+b,0)/recent.length*100);return {pct,attempts:x.total,mastered:x.total>=5&&recent.length>=5&&pct>=80};}
  function shuffle(a){const out=[...a];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]];}return out;}
  function keyFor(mode,unit){return mode==='unit'?`unit-${unit}`:mode;}
  function buildDeck(mode,unit){let pool=bank;if(mode==='unit')pool=bank.filter(q=>q.unit===unit);if(mode==='missed'){const p=load(),ids=new Set(Object.values(p).flatMap(x=>x.missed||[]));pool=bank.filter(q=>ids.has(q.id));}
    const count=mode==='unit'?25:30; const seen=loadSeen(); const k=keyFor(mode,unit); const recent=new Set(seen[k]||[]);
    let fresh=pool.filter(q=>!recent.has(q.id)); if(fresh.length<count)fresh=pool;
    const picked=shuffle(fresh).slice(0,Math.min(count,fresh.length)).map(q=>({...q,choices:shuffle(q.choices)}));
    seen[k]=picked.map(q=>q.id).slice(-Math.min(80,picked.length)); saveSeen(seen); return picked;
  }
  function start(mode,unit){state={mode:'session',unit:unit||1,deck:[],index:0,selected:null,session:[]};state.deck=buildDeck(mode,unit||1);render();}
  window.pmStart=start;window.pmChoose=i=>{if(state.selected!==null)return;const q=state.deck[state.index];state.selected=i;const ok=q.choices[i]===q.answer;record(q,ok);state.session.push({q,correct:ok});render();};window.pmNext=()=>{state.index++;state.selected=null;if(state.index>=state.deck.length)state.mode='results';render();};window.pmDashboard=()=>{state.mode='dashboard';render();};window.pmReset=()=>{if(confirm('Reset Practice & Mastery progress?')){localStorage.removeItem(storeKey);localStorage.removeItem(seenKey);state.mode='dashboard';render();}};
  const oldRender=render;render=function(){if(active==='practiceMastery'){renderNav();document.getElementById('app').innerHTML=page();return;}oldRender();};
  function page(){return `<main class="wrap">${state.mode==='dashboard'?dash():state.mode==='session'?session():results()}</main>`;}
  function dash(){const topics=[...new Set(bank.map(q=>q.topic))],stats=topics.map(t=>[t,score(t)]),attempted=stats.filter(x=>x[1]),mastered=stats.filter(x=>x[1]?.mastered),p=load(),missed=Object.values(p).reduce((n,x)=>n+(x.missed||[]).length,0);return `<section class="card"><h2>🎯 Practice & Mastery</h2><p><b>${bank.length.toLocaleString()} practice variants</b> across ${topics.length} CED topics. Repeated tests rotate wording and recently seen variants, and answer choices are reshuffled. Mastery requires at least 5 attempts and 80%+ recent accuracy.</p><div class="readiness-grid"><div class="readiness-tile"><b>${mastered.length}/${topics.length}</b><span>topics mastered</span></div><div class="readiness-tile"><b>${attempted.length}</b><span>topics attempted</span></div><div class="readiness-tile"><b>${missed}</b><span>missed to review</span></div></div><div class="button-row">${[1,2,3,4,5,6,7].map(u=>`<button class="btn-secondary" onclick="pmStart('unit',${u})">Unit ${u} · 25 Q</button>`).join('')}<button class="btn-primary" onclick="pmStart('cumulative')">Cumulative · 30 Q</button><button class="btn-secondary" onclick="pmStart('missed')" ${missed?'':'disabled'}>Review Missed</button><button class="btn-secondary" onclick="pmReset()">Reset</button></div></section><section class="card"><h3>CED Topic Readiness</h3><div class="readiness-grid">${stats.map(([t,s])=>`<div class="readiness-tile"><b>${s?s.pct+'%':'—'}</b><span>${t}${s?.mastered?' ✓ Mastered':s?' · '+s.attempts+' attempts':''}</span></div>`).join('')}</div></section>`;}
  function session(){if(!state.deck.length)return `<section class="card"><h2>No questions in this queue yet</h2><button class="btn-primary" onclick="pmDashboard()">Back</button></section>`;const q=state.deck[state.index],sel=state.selected;return `<section class="card"><div class="mastery-mini-nav"><span class="pill">Unit ${q.unit} · Topic ${q.topic}</span><span>${state.index+1}/${state.deck.length}</span></div><h2>${q.prompt}</h2><div class="quiz-options">${q.choices.map((c,i)=>`<button class="quiz-option ${sel!==null&&c===q.answer?'correct':sel===i&&c!==q.answer?'wrong':''}" onclick="pmChoose(${i})" ${sel!==null?'disabled':''}>${String.fromCharCode(65+i)}. ${c}</button>`).join('')}</div>${sel!==null?`<div class="${q.choices[sel]===q.answer?'box-good':'box-warn'}"><b>${q.choices[sel]===q.answer?'Correct':'Not yet'}</b><p>${q.explain}</p></div><button class="btn-primary" onclick="pmNext()">${state.index+1===state.deck.length?'Results':'Next →'}</button>`:''}</section>`;}
  function results(){const r=state.session.filter(x=>x.correct).length,t=state.session.length,p=t?Math.round(r/t*100):0,weak=[...new Set(state.session.filter(x=>!x.correct).map(x=>x.q.topic))];return `<section class="card"><h2>Practice Results</h2><div class="readiness-grid"><div class="readiness-tile"><b>${r}/${t}</b><span>correct</span></div><div class="readiness-tile"><b>${p}%</b><span>score</span></div><div class="readiness-tile"><b>${weak.length}</b><span>topics to revisit</span></div></div>${weak.length?`<div class="box-warn"><b>Revisit:</b> ${weak.join(', ')}</div>`:`<div class="box-good"><b>Strong session.</b> Keep spacing practice over time.</div>`}<div class="button-row"><button class="btn-primary" onclick="pmDashboard()">Dashboard</button><button class="btn-secondary" onclick="pmStart('missed')">Review Missed</button></div></section>`;}
})();