(function(){
  'use strict';
  const engine=window.APHGTeacherAssessment,root=document.getElementById('student-quiz'),params=new URLSearchParams(location.search);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const bank=window.APHGAssessmentBank.all();
  const ids=(params.get('ids')||'').split(',').filter(Boolean),seed=params.get('seed')||'',title=(params.get('title')||'Assigned Quiz').slice(0,100),version=(params.get('version')||'A').slice(0,1);
  let questions=[];
  function renderError(message){root.innerHTML=`<section class="notice"><h2>This quiz link cannot be opened</h2><p>${esc(message)}</p><p>Ask your teacher for a new link.</p></section>`}
  try{if(!ids.length||ids.length>40)throw new Error('The link does not contain a valid quiz.');questions=engine.assemble(bank,ids,seed)}catch(error){renderError(error.message);return}
  document.title=`${title} | APHUG Study Buddy`;document.getElementById('quiz-title').textContent=`${title} — Version ${version}`;document.getElementById('quiz-meta').textContent=`${questions.length} questions · Topics ${[...new Set(questions.map(q=>q.topic))].join(', ')}`;
  function question(q,i){return `<section class="quiz-question" data-index="${i}"><span class="topic-tag">Topic ${esc(q.topic)}</span><fieldset><legend>${i+1}. ${esc(q.prompt)}</legend>${q.visual?`<figure>${q.visual}<figcaption>${esc(q.stimulusTitle)}${q.source?' · '+esc(q.source):''}</figcaption></figure>`:''}${q.choices.map((choice,j)=>`<label class="choice"><input type="radio" name="q${i}" value="${j}"> <span><b>${String.fromCharCode(65+j)}.</b> ${esc(choice)}</span></label>`).join('')}</fieldset><div class="feedback"></div></section>`}
  root.innerHTML=`<section class="notice"><b>Directions:</b> Choose the best answer. You may change answers until you submit. Explanations appear after submission.</section>${questions.map(question).join('')}<div class="submit-bar"><button id="submit-quiz">Submit quiz</button></div>`;
  document.getElementById('submit-quiz').addEventListener('click',()=>{const unanswered=questions.filter((q,i)=>!document.querySelector(`input[name="q${i}"]:checked`)).length;if(unanswered&&!confirm(`${unanswered} question${unanswered===1?' is':'s are'} unanswered. Submit anyway?`))return;let correct=0;const byTopic={};questions.forEach((q,i)=>{const selected=document.querySelector(`input[name="q${i}"]:checked`),choice=selected?q.choices[Number(selected.value)]:null,ok=choice===q.answer;if(ok)correct++;byTopic[q.topic]??={right:0,total:0};byTopic[q.topic].total++;if(ok)byTopic[q.topic].right++;document.querySelectorAll(`input[name="q${i}"]`).forEach(input=>{input.disabled=true;const label=input.closest('.choice'),value=q.choices[Number(input.value)];if(value===q.answer)label.classList.add('correct');else if(input.checked)label.classList.add('incorrect')});document.querySelector(`[data-index="${i}"] .feedback`).innerHTML=`<div class="explanation"><b>${ok?'Correct':'Correct answer: '+String.fromCharCode(65+q.choices.indexOf(q.answer))}</b><br>${esc(q.explanation)}</div>`});const pct=Math.round(correct/questions.length*100);root.insertAdjacentHTML('afterbegin',`<section class="results" id="results" tabindex="-1"><div class="score">${correct}/${questions.length} · ${pct}%</div><p>This is your result on this device. Show or submit it as your teacher directs.</p><div class="topic-results">${Object.entries(byTopic).map(([topic,r])=>`<span><b>${topic}:</b> ${r.right}/${r.total}</span>`).join('')}</div></section>`);document.querySelector('.submit-bar').remove();document.getElementById('results').focus()});
})();
