(function(){
  'use strict';
  const engine=window.APHGTeacherAssessment;
  let assessment=[],version='A',revision=0;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function bank(){const base=(typeof quiz!=='undefined'?quiz:[]).filter(q=>String(q[0])==='Unit 1');return engine.buildBank([...base,...(window.APHG_UNIT1_VISUAL_ASSESSMENT_BANK||[])])}
  function settings(suffix=''){return {units:[1],count:Number(document.getElementById('question-count').value),difficulty:document.getElementById('difficulty').value,visualRate:document.getElementById('visual-rate').value,seed:`unit1-${version}-${document.getElementById('assessment-title').value}-${suffix}`}}
  function build(){try{assessment=engine.select(bank(),settings());revision=0;render();document.getElementById('builder-status').textContent=`Created Version ${version}: ${assessment.length} vetted questions, ${assessment.filter(q=>q.visual).length} with visual stimuli.`}catch(error){document.getElementById('builder-status').textContent=error.message}}
  function replace(index){const old=assessment[index],excluded=new Set(assessment.map(engine.signature));const pool=bank().filter(q=>!excluded.has(engine.signature(q)));const close=pool.filter(q=>q.topic===old.topic&&Boolean(q.visual)===Boolean(old.visual));const next=engine.shuffle(close.length?close:pool,`${settings().seed}-${old.id}-${revision++}`)[0];if(next){assessment[index]=next;render()}}
  function remove(index){if(assessment.length>5){assessment.splice(index,1);render()}}
  function newVersion(){version=version==='A'?'B':'A';build()}
  function question(q,i,key=false){const letters=['A','B','C','D'];return `<article class="teacher-question"><div class="question-heading"><b>${i+1}. ${esc(q.prompt)}</b><span>Topic ${esc(q.topic)} · ${q.visual?'Stimulus':'No stimulus'}</span></div>${q.visual?`<figure>${q.visual}<figcaption>${esc(q.stimulusTitle)} · ${esc(q.source)}</figcaption></figure>`:''}<ol class="answer-choices" type="A">${q.choices.map(c=>`<li class="${key&&c===q.answer?'correct-answer':''}">${esc(c)}</li>`).join('')}</ol>${key?`<div class="answer-explanation"><b>Answer: ${letters[q.choices.indexOf(q.answer)]}</b> — ${esc(q.explanation)}</div>`:`<div class="question-actions no-print"><button data-action="replace" data-index="${i}">Replace</button><button data-action="remove" data-index="${i}">Remove</button></div>`}</article>`}
  function render(){const title=esc(document.getElementById('assessment-title').value||'Unit 1 Assessment');document.getElementById('assessment-preview').innerHTML=assessment.length?`<section class="print-page"><header class="test-header"><div><h1>${title} — Version ${version}</h1><p>AP Human Geography · Unit 1: Thinking Geographically</p></div><div class="student-line">Name: ____________________</div></header><p class="directions">Choose the best answer for each question. Use the stimulus when one is provided.</p>${assessment.map((q,i)=>question(q,i)).join('')}</section><section class="print-page answer-key"><h1>${title} — Answer Key, Version ${version}</h1>${assessment.map((q,i)=>question(q,i,true)).join('')}</section>`:'<div class="empty-state">Choose your settings and select <b>Create assessment</b>.</div>'}
  document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const i=Number(button.dataset.index);if(button.dataset.action==='replace')replace(i);if(button.dataset.action==='remove')remove(i)});
  document.getElementById('create-assessment').addEventListener('click',build);document.getElementById('new-version').addEventListener('click',newVersion);document.getElementById('print-assessment').addEventListener('click',()=>window.print());render();
})();
