(function(){
  'use strict';
  const engine=window.APHGTeacherAssessment;
  let assessment=[],version='A',revision=0,currentSeed='';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function bank(){return window.APHGAssessmentBank.all()}
  function selectedTopics(){return [...document.querySelectorAll('[name="ced-topic"]:checked')].map(x=>x.value)}
  function settings(suffix=''){const unit=Number(document.getElementById('unit-select').value);return {units:[unit],topics:selectedTopics(),count:Number(document.getElementById('question-count').value),difficulty:document.getElementById('difficulty').value,visualRate:document.getElementById('visual-rate').value,seed:`unit${unit}-${version}-${document.getElementById('assessment-title').value}-${suffix}`}}
  function topicData(unit){return (window.APHGCEDGuide?.allTopics?.()||[]).filter(t=>t.unit===Number(unit))}
  function renderTopics(){const unit=document.getElementById('unit-select').value;document.getElementById('topic-options').innerHTML=topicData(unit).map(t=>`<label class="topic-choice"><input type="checkbox" name="ced-topic" value="${t.id}" checked> <span><b>${t.id}</b> ${esc(t.title)}</span></label>`).join('');document.getElementById('assessment-title').value=`Unit ${unit} Topics Quiz`;updateAvailable()}
  function updateAvailable(){const unit=Number(document.getElementById('unit-select').value),topics=selectedTopics();const total=bank().filter(q=>q.unit===unit&&(!topics.length||topics.includes(String(q.topic)))).length;document.getElementById('available-count').textContent=`${total} vetted questions available for the selected topics.`}
  function build(){try{const opts=settings();if(!opts.topics.length)throw new Error('Choose at least one CED topic.');assessment=engine.select(bank(),opts);currentSeed=opts.seed;revision=0;render();document.getElementById('builder-status').textContent=`Created Version ${version}: ${assessment.length} vetted questions across ${opts.topics.join(', ')}.`}catch(error){document.getElementById('builder-status').textContent=error.message}}
  function rebalance(ids){assessment=engine.assemble(bank(),ids,currentSeed)}
  function replace(index){const old=assessment[index],excluded=new Set(assessment.map(engine.signature)),allowed=new Set(selectedTopics());const pool=bank().filter(q=>!excluded.has(engine.signature(q))&&allowed.has(String(q.topic)));const close=pool.filter(q=>q.topic===old.topic&&Boolean(q.visual)===Boolean(old.visual));const next=engine.shuffle(close.length?close:pool,`${currentSeed}-${old.id}-${revision++}`)[0];if(next){const ids=assessment.map(q=>q.id);ids[index]=next.id;rebalance(ids);render()}}
  function remove(index){if(assessment.length>5){const ids=assessment.map(q=>q.id);ids.splice(index,1);rebalance(ids);render()}}
  function newVersion(){version=version==='A'?'B':'A';build()}
  function studentUrl(){const params=new URLSearchParams({ids:assessment.map(q=>q.id).join(','),seed:currentSeed,title:document.getElementById('assessment-title').value,version});return `${location.origin}/student-quiz.html?${params}`}
  function showLink(){if(!assessment.length){document.getElementById('builder-status').textContent='Create an assessment before making a student link.';return}const url=studentUrl(),box=document.getElementById('student-link-box');box.hidden=false;box.querySelector('input').value=url;box.querySelector('a').href=url}
  async function copyLink(){showLink();const input=document.querySelector('#student-link-box input');if(!input.value)return;try{await navigator.clipboard.writeText(input.value);document.getElementById('builder-status').textContent='Student quiz link copied.'}catch(e){input.select();document.getElementById('builder-status').textContent='Select and copy the student quiz link shown below.'}}
  function question(q,i,key=false){const letters=['A','B','C','D'];return `<article class="teacher-question"><div class="question-heading"><b>${i+1}. ${esc(q.prompt)}</b><span>Topic ${esc(q.topic)} · ${q.visual?'Stimulus':'No stimulus'}</span></div>${q.visual?`<figure>${q.visual}<figcaption>${esc(q.stimulusTitle)}${q.source?' · '+esc(q.source):''}</figcaption></figure>`:''}<ol class="answer-choices" type="A">${q.choices.map(c=>`<li class="${key&&c===q.answer?'correct-answer':''}">${esc(c)}</li>`).join('')}</ol>${key?`<div class="answer-explanation"><b>Answer: ${letters[q.choices.indexOf(q.answer)]}</b> — ${esc(q.explanation)}</div>`:`<div class="question-actions no-print"><button data-action="replace" data-index="${i}">Replace</button><button data-action="remove" data-index="${i}">Remove</button></div>`}</article>`}
  function render(){const title=esc(document.getElementById('assessment-title').value||'APHG Quiz'),unit=document.getElementById('unit-select').value;document.getElementById('assessment-preview').innerHTML=assessment.length?`<section class="print-page"><header class="test-header"><div><h1>${title} — Version ${version}</h1><p>AP Human Geography · Unit ${unit} · Topics ${[...new Set(assessment.map(q=>q.topic))].join(', ')}</p></div><div class="student-line">Name: ____________________</div></header><p class="directions">Choose the best answer for each question. Use the stimulus when one is provided.</p>${assessment.map((q,i)=>question(q,i)).join('')}</section><section class="print-page answer-key"><h1>${title} — Answer Key, Version ${version}</h1>${assessment.map((q,i)=>question(q,i,true)).join('')}</section>`:'<div class="empty-state">Choose a unit and the topics you taught, then select <b>Create assessment</b>.</div>'}
  document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(!button)return;const i=Number(button.dataset.index);if(button.dataset.action==='replace')replace(i);if(button.dataset.action==='remove')remove(i)});
  document.getElementById('unit-select').addEventListener('change',renderTopics);document.getElementById('topic-options').addEventListener('change',updateAvailable);document.getElementById('create-assessment').addEventListener('click',build);document.getElementById('new-version').addEventListener('click',newVersion);document.getElementById('print-assessment').addEventListener('click',()=>window.print());document.getElementById('make-student-link').addEventListener('click',showLink);document.getElementById('copy-student-link').addEventListener('click',copyLink);renderTopics();render();
})();
